# Generated by Django 5.0.2 on 2024-03-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propietarios_Mascotas', '0002_mascota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mascota',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
