# Generated by Django 5.0.2 on 2024-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Propietarios_Mascotas', '0003_delete_mascota_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('documento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('nombreEmer', models.CharField(max_length=50)),
                ('telefonoEmer', models.CharField(max_length=10)),
            ],
        ),
    ]
