# Generated by Django 5.0.2 on 2024-03-03 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propietarios_Mascotas', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReproductivo',
            fields=[
                ('idEstadoReproductivo', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotosMascotas')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('color', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('meses', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rh', models.CharField(max_length=3)),
                ('personalidad', models.CharField(max_length=100)),
                ('alimentacion', models.CharField(max_length=100)),
                ('cantidadAlimento', models.CharField(max_length=100)),
                ('frecuenciaAlimentacion', models.CharField(max_length=100)),
                ('frecuenciaBano', models.CharField(max_length=100)),
                ('antecedentesClinicos', models.CharField(max_length=100, null=True)),
                ('EstadoReproductivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propietarios_Mascotas.estadoreproductivo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propietarios_Mascotas.propietario')),
            ],
        ),
    ]
