# Generated by Django 5.0.2 on 2024-03-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propietarios_Mascotas', '0005_estadoreproductivo_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
